### ISSUE TITLE
Error to create config.txt

### ISSUE THREAD

**Issue by drumair** [mzytnicki/mmannot#1]
ValueError: need more than 1 value to unpack

Hi, 
I am getting following error when I use the GTF file from ensembl.org ftp://ftp.ensembl.org/pub/release-101/gtf/homo_sapiens/Homo_sapiens.GRCh38.101.gtf.gz
or GENCODE gtf files
To create config.txt

Traceback (most recent call last):
  File "./createConfigFile", line 247, in <module>
    for source, type, id, parents in fileParser.parse():
  File "./createConfigFile", line 219, in parse
    key, value = tag.strip().split(keyValueSeparator, 1)
ValueError: need more than 1 value to unpack

**Comment by mzytnicki** [comment]
Sorry for being so slow to answer.
I did correct the bug.  Thanks!
